# ## TODO: Uncomment this file
#
# ## This file builds Docker images of this repo
# ## You must create the repo and registry secrets separately in our Drone instance

# name: # FILL ME IN - builds branches
# kind: pipeline
# type: kubernetes

# platform:
#   os: linux
#   arch: amd64

# steps:
#   - name: publish-sha
#     image: plugins/ecr
#     settings:
#       repo:
#         from_secret: ecr_repo
#       registry:
#         from_secret: ecr_registry
#       region: us-east-1
#       tags:
#         - ${DRONE_COMMIT_SHA}
# trigger:
#   event:
#     exclude:
#     - pull_request
# node_selector:
#   drone-builds: true
# ---
# name: # FILL ME IN - builds main
# kind: pipeline
# type: kubernetes

# platform:
#   os: linux
#   arch: amd64

# steps:
#   - name: publish  
#     image: plugins/ecr
#     settings:
#       repo:
#         from_secret: ecr_repo
#       registry:
#         from_secret: ecr_registry
#       region: us-east-1
#       tags:
#         - latest

# trigger:
#   branch:
#   - main
#   event:
#     include:
#       - push
# node_selector:
#   drone-builds: true
