version: '3'
services:
    postgres:
        image: postgres:11.7
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=fakepassword
            - POSTGRES_DB=postgres
        # persist the postgres data to disk so we don't lose it
        # on rebuilds.
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - 5433:5432
    hashalytics:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=api
            - POSTGRES_DB=hashalytics
        volumes:
            - ./postgres-hashalytics:/var/lib/postgresql/data
        ports:
            - 5432:5432
    hashalytics_migrations:
        # todo: change to :latest tag when the PR in 0x-pipeline-orchestration lands
        image: 883408475785.dkr.ecr.us-east-1.amazonaws.com/0x-pipeline-orchestration/pipeline/migrations:ada26430cb61a9d8169527661f156c85ec87f2e1
        depends_on:
            - hashalytics
        environment:
            - ZEROEX_DATA_PIPELINE_DB_URL=postgresql://api:api@hashalytics/hashalytics
        
