# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on: [push]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install --frozen-lockfile
    - run: yarn build:ts
    - run: yarn lint
    - run: docker-compose up postgres
    - run: yarn migrate
    - run: yarn test
    - run: docker-compose down
    - name: Save build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: lib
        path: lib
